# Generated by Django 4.1.5 on 2024-02-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='atendido',
            field=models.BooleanField(default=False, verbose_name='Atendido?'),
        ),
    ]
