# Generated by Django 4.1.5 on 2024-02-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('forma_identificacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Forma de Identificação')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
