# Generated by Django 4.1.5 on 2024-02-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='forma_identificacao',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Forma de Identificação'),
        ),
    ]
