# Generated by Django 4.1.5 on 2024-02-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_forma_identificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='na_fila',
            field=models.BooleanField(default=False, verbose_name='Na Fila'),
        ),
    ]
